ci -l bkdia.tex
ci -l bkfzch1.tex
ci -l bkfzch2.tex
ci -l bkfzch3.tex
ci -l bkfzch4.tex
ci -l bkfzhead.tex
ci -l bkfzpre.tex
ci -l bkfztitle.tex
ci -l bkjz.tex
ci -l bkmz.tex
ci -l bktry.tex
ci -l bktz.tex
ci -l rundia.tex
ci -l runfz.tex
ci -l runfzch2.tex
ci -l runjz.tex
ci -l runmz.tex
ci -l runtry.tex
ci -l runtz.tex
ci -l zreffmt.tex
ci -l zreffmtfz.tex
ci -l zrefman.sty
