      SUBROUTINE XECHO
      CHARACTER*80 STRING
      CHARACTER*6 CMINUS, OPTION
      CHARACTER*8 CHRSET, FORMAT

      CALL KUGETS(STRING, LSTR)
      CALL KUGETI(NUMBER)
      CALL KUGETC(CMINUS, LMIN)
      CALL KUGETR(POSTIV)
      CALL KUGETC(OPTION, LOPT)
      CALL KUGETC(CHRSET, LCHS)
      CALL KUGETC(FORMAT, LFMT)

      PRINT '(A,I3,3A,F4.2,6A/)',
     +  ' NUMBER=',NUMBER,
     +  '  MINUS=',CMINUS,
     +  ' POSITIVE=',POSTIV,
     +  '  OPTION=',OPTION,
     +  ' CHARSET=',CHRSET,
     +  ' FORMAT=',FORMAT

      END
