ALL= a.xml a.new.xml a.new.pdf

all: $(ALL)

a.xml: a.tex 
	htlatex a.tex "xhtml,tei.4ht,unicode.4ht,mathml.4ht,tei-mml.4ht,tei-mmltei.4ht" "unicode"
	rxp -V -s a.xml

a.new.xml: a.xml
	saxonxsl a.xml xml2xml.xsl >  a.new.xml
	rxp -V -s a.new.xml 

a.new.pdf: a.new.xml
	saxonxsl a.new.xml /afs/cern.ch/project/tex/xml/tei/tei-fo/tei.xsl >  a.new.fo
	pdfxmltex a.new.fo
	pdfxmltex a.new.fo

