$external_labels{"LZLONG"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"LZHEAD"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"MZMARK"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"LZFVAL"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"NZBANK"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"ZSORVH"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"ZSORV"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"LZSCAN"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"NZFIND"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"ZSORT"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"LZBYT"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"ZTOPSY"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"MZFLAG"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"secH1Datastructureutilities"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"LZFIND"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"ZSORTI"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"NZLONG"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"LZFID"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"ZPRESS"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"ZSHUNT"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"ZSORTH"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"LZLAST"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"LZFIDH"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"MZVOLM"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 
$external_labels{"ZSORVI"} ="../../zebra/ZEBMZ2/chapter2_1.html"; 

1;
